1 1 anlegen der seite impressum
vitrum-connect/5gla-react pull request #3
Opened 2024-11-05 14:56 UTC by BSO-Jannis

Text embedded within the impressum-page is just used as example text from user story to file the page

2024-11-06 12:42 UTC, saschadoemer requested changes
In der Grundstruktur sind noch einige Dinge, die keinen Sinn mehr ergeben. D.h. beispielsweise die Tests der App oder auch das Setup der Tests. Die sollten auch entsprechend raus.

2024-11-06 12:45 UTC, saschadoemer commented
Der Build und die Integration der Dependencies wirft wirklich viele Warnings bzgl. bereits deaktivierter oder auch nicht mehr zu nutzender Packages. Das solltest du dir vorher anschauen.

<img width="1668" alt="image" src="https://github.com/user-attachments/assets/ee05a3f8-b91d-4554-b113-69d16f519fa4">

2024-11-06 12:46 UTC, saschadoemer commented
In der Grundstruktur liegen auch noch die alten Logos, wie auch die CSS? Welche Daten werden da noch gebraucht?

2024-11-06 12:52 UTC, saschadoemer commented
Der `public` Ordner scheint auch noch ein Relikt der vorherigen Struktur zu sein.

2024-11-07 08:36 UTC, BSO-Jannis commented
> Der Build und die Integration der Dependencies wirft wirklich viele Warnings bzgl. bereits deaktivierter oder auch nicht mehr zu nutzender Packages. Das solltest du dir vorher anschauen.
> 
> <img alt="image" width="1668" src="https://private-user-images.githubusercontent.com/1309344/383557682-ee05a3f8-b91d-4554-b113-69d16f519fa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjcxMDksIm5iZiI6MTczMDk2NjgwOSwicGF0aCI6Ii8xMzA5MzQ0LzM4MzU1NzY4Mi1lZTA1YTNmOC1iOTFkLTQ1NTQtYjExMy02OWQxNmY1MTlmYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMDgwNjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDdkOWY1YzFiMzFlOTBlNzc1MDkwY2QxOWY2MWViNzg4NzYxZmU5NmJmMjdjNzg4NmZhNGUwODIzOTc0NjVmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7VQTkYiHm1Piv-MkMysGOwI23KhCZU55MwvR-dBPMXw">


Ich habe mir nochmal tiefer eingelesen in die Warning Geschichte: Hier ein Beitrag dazu: https://github.com/facebook/create-react-app/issues/11174 scheint dann eine Problematik mit npm zu sein. Soll ich dann react-scripts unter devDependencies anlegen, oder so lassen wie es aktuell ist?

2024-11-08 08:18 UTC, saschadoemer approved these changes

2024-11-08 08:18 UTC, saschadoemer commented on 5gla-react-app/src/components/Footer/Footer.js
> +      <Link
Das sollte normalerweise über SCSS / CSS gesteuert werden. Inline-CSS wird nicht skalieren.

2024-11-08 08:18 UTC, merged